[alias]
today = "run --quiet --release --features today -- today"
scaffold = "run --quiet --release -- scaffold"
download = "run --quiet --release -- download"
read = "run --quiet --release -- read"

solve = "run --quiet --release -- solve"
all = "run --quiet --release -- all"
time = "run --quiet --profile bench -- time"

[env]
AOC_YEAR = "2024"

[build]
rustflags = ["-C", "target-cpu=native"]